name: Quarkus Criteria Build

on: [push, pull_request]

jobs:
  build:
    name: Quarkus criteria Build, Test & Run
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [11.0.4, 13, 15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build & Test
        run: mvn clean verify -Pcoverage
      - name: Run it tests app
        run: java -jar it-tests/target/quarkus-criteria-it-runner.jar
  report:
    name: Report
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Coverage report
        run: mvn coveralls:report -DCOVERAGE_TOKEN=${{ secrets.COVERAGE_TOKEN }} -Pcoverage