name: Quarkus Criteria Build

on: [push, pull_request]

jobs:
  build:
    name: Quarkus criteria Build, Test & Run
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [11.0.4, 13, 15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build & Test
        run: mvn clean install -Pcoverage
      - name: Run it tests application
        run: java -jar it-tests/target/quarkus-app/quarkus-run.jar
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: |
            coverage-report/target/site/jacoco-aggregate/*
            it-tests/*
  report:
    name: Coverage Report
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - uses: actions/download-artifact@master
        with:
          name: output
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Coverage report
        run: mvn coveralls:report -DCOVERAGE_TOKEN=${{ secrets.COVERAGE_TOKEN }} -Pcoverage
  native:
    name: Native tests
    runs-on: ubuntu-18.04
    needs: report
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Pull docker image
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:20.3.0-java11
      - name: Run integration tests in native
        run: mvn install -DskipTests && mvn verify -f system-tests/pom.xml -Ddocker -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:20.3.0-java11 -Pnative
  deploy:
    name: Deploy snapshots
    runs-on: ubuntu-18.04
    needs: native
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Deploy snapshots
        run: mvn deploy -Prelease --settings settings.xml -DMAVEN.USER=${{secrets.MAVEN_USER}} -DMAVEN.PASS=${{secrets.MAVEN_PASS}}