name: Quarkus Criteria Build

on: [push, pull_request]

jobs:
  build:
    name: Quarkus criteria Build, Test & Run
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [11.0.4, 13, 15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build & Test
        run: mvn clean package
      - name: Run app
        run: java -jar system-tests/target/quarkus-criteria-st-runner.jar